spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.29.142.129:3306/litemall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

server:
  servlet:
    context-path: /test
